from pathlib import Path
import yaml,json,shutil
p=Path('specs/041-popcorn-feedback-and-learning');ev=p/'evidence';arc=ev/'review-before-completion-popup-copy';arc.mkdir(exist_ok=True)
for name in ['map.yaml','learning-content.yaml','spec.md','plan.md','review.md','approval.yaml']:shutil.copy2(p/name,arc/name)
for name in ['preview.svg','preview.html','implementation.yaml','review-manifest.json','learning-review.html']:shutil.copy2(p/'generated'/name,arc/name)
shutil.copy2(ev/'approval-lineage.json',arc/'approval-lineage.json')
old=json.loads((arc/'review-manifest.json').read_text())['review_digest'];lesson='Mission complete! You saved three steps and reused them.';action='You can return to the hub. Use Return.'
copy=yaml.safe_load((p/'learning-content.yaml').read_text(encoding='utf-8'));r=next(x for x in copy['rows'] if x['id']=='final_done');before=dict(r);r['lesson']=lesson;r['action']=action
card='\n'.join([lesson,copy['recipe_after_commit'],action]);assert len(card)==126
(p/'learning-content.yaml').write_text(yaml.safe_dump(copy,sort_keys=False,allow_unicode=True),encoding='utf-8')
d=yaml.safe_load((p/'map.yaml').read_text(encoding='utf-8'));ctrl=next(x for x in d['devices'] if x['id']=='controller');ctrl['settings']['learning_content']=copy
ctrl['settings']['completion_popup_copy_refinement']={'owner_request':'When hitting the last pop039_ring_7 add a popup to user, that they completed the mission and can return to the hub','existing_event':'Target7 successful fixtures.complete -> committed_lesson -> advance_lesson final_done, owner HUD and final board','card_chars':126,'card':card,'unchanged':'No raw-hit completion or extra trigger/device; existing commit/cancellation/reward/Return guards preserved'}
(p/'map.yaml').write_text(yaml.safe_dump(d,sort_keys=False,allow_unicode=True),encoding='utf-8')
q=p/'spec.md';s=q.read_text(encoding='utf-8');s+='''\n## Owner-requested completion popup clarity refinement — 2026-10-08\n\nOwner: “When hitting the last pop039_ring_7 add a popup to user, that they completed the mission and can return to the hub”. R09: successful target7 commit displays the existing owner HUD popup with explicit mission-complete wording and hub Return instruction. Reuse final_done; no new device/modal/trigger, gameplay or reward change. Exact three-line126-character card:\n\n```text\nMission complete! You saved three steps and reused them.\nPopBridge = LOAD > HEAT > POP.\nYou can return to the hub. Use Return.\n```\n\nA09 [R04,R05,R06,R07,R09]: Given the actual finish landing and valid branch/owner/attempt, when the final ring7 shot successfully commits the existing routine, then the owner sees that exact completion popup and existing Return can take them to the hub. An early/rejected/stale/cancelled final shot does not say mission complete; no duplicate reward/new interaction occurs. Given journal open, latest completed card follows existing masking/resume policy. Verification remains owner manual; no testing requested.\n''';q.write_text(s,encoding='utf-8')
q=p/'plan.md';s=q.read_text(encoding='utf-8');s+='''\n## Completion popup copy refinement (direct owner request)\n\nThe implemented controller already calls committed_lesson only after fixtures.complete succeeds. Production committed_lesson selects final_done, advance_lesson renders the existing owner HUD, and target7 also writes the same card to final_board. Owner wants that popup to explicitly say the mission is complete and they can return to the hub. Change only final_done lesson/action in learning-content.yaml; preserve recipe row. Card126 characters including two newlines, below even the older150-character limit. No new trigger, popup device, modal, asset, target property, native setting, layout or progression change.\n\nImplementation handoff: run existing tools/build_popbridge_production.py to regenerate production lesson_line/action_line from the synchronized authored table; inspect source delta limited to the two final_done literals, then build changed Verse and save under Supervisor/Implementer ownership. Native mutation is unnecessary for this copy because production startup/committed event owns board/HUD content. Keep final_pending unchanged until successful commit and keep all guard/reward paths. Do not edit generator/template/controller transition rules. Manual acceptance A09 plus Return/Replay/reward preservation remains unrun; no automatic tests, QA, Project Validate, cook, push or session. Actual owner request directly authorizes this nonmaterial copy refinement; no approval re-request or fabricated new approval.\n''';q.write_text(s,encoding='utf-8')
q=p/'review.md';s=q.read_text(encoding='utf-8');s+='''\n## Completion popup copy refinement review\n\nOffline source inspection confirms controller fixtures.complete success precedes committed_lesson; production final_done already renders persistent owner HUD and final_board. Owner's new request therefore needs only two authored copy literals. Full card126 characters, unchanged recipe, no added mechanism/interaction. Pending/invalid hits cannot truthfully claim completion and keep their existing messages. Original approved popup wording is archived under evidence/review-before-completion-popup-copy; direct owner request authorizes explicit mission-complete/Return clarity. Source inspection is not gameplay evidence; manual verification remains outstanding.\n''';q.write_text(s,encoding='utf-8')
q=p/'generated/learning-review.html';s=q.read_text(encoding='utf-8').replace(before['lesson'],lesson).replace(before['action'],action);q.write_text(s,encoding='utf-8')
report={'owner_request':'When hitting the last pop039_ring_7 add a popup to user, that they completed the mission and can return to the hub','prior_review_digest':old,'changed_row':'final_done','before':before,'after':r,'card':card,'card_chars':len(card),'trigger_preserved':'Successful target7 commit only, existing owner HUD and final_board','source_evidence':['Content/fn_shoreline_island_popbridge_controller.verse execute complete success','Content/fn_shoreline_island_popbridge_production.verse committed_lesson/advance_lesson final_done'],'new_device_or_gameplay_change':False,'original_human_approval_preserved':True,'new_approval_requested_or_fabricated':False,'tests_run':False,'archive':'evidence/review-before-completion-popup-copy'}
(ev/'completion-popup-copy-refinement.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print('Authored final_done card126 chars; existing commit/popup reused.')
