from pathlib import Path
import json,yaml,shutil,hashlib,wave
p=Path('specs/041-popcorn-feedback-and-learning'); ev=p/'evidence'; ar=ev/'review-before-audio-permission-repair'; ar.mkdir(exist_ok=True)
for name in ['map.yaml','plan.md','approval.yaml']:
 shutil.copy2(p/name,ar/name)
for name in ['preview.svg','preview.html','implementation.yaml','review-manifest.json']:
 shutil.copy2(p/'generated'/name,ar/name)
shutil.copy2(ev/'resolved-native-configuration.json',ar/'resolved-native-configuration.json');shutil.copy2(ev/'approval-lineage.json',ar/'approval-lineage.json')
config=json.loads((ev/'resolved-native-configuration.json').read_text(encoding='utf-8'));cfg=config['audio']
asset='/fn_shoreline_island/Audio/popcorn_hit_original.popcorn_hit_original';oldasset=cfg['native_values']['audio']['refPath'];cfg['native_values']['audio']['refPath']=asset;cfg['source_duration_seconds']=0.175
cfg['source_provenance']={'source_wav':'Resources/Audio/popcorn_hit_original.wav','generator':'tools/create_popcorn_hit_audio.py','original_synthesized_audio':True,'sha256':'0ffa24c83dea5dd2011e1d3082cd31a187395221c786b16c1ef8afb7ba05841b','format':'48000Hz mono16-bit PCM,8400 frames','native_evidence':'evidence/original-pop-audio-provenance-imported.json','native_dependencies':[]}
cfg['lifecycle']='Explicit existing accept Play(agent), same epoch-guarded Stop(agent) at0.175s plus0.025s fade; original project-owned source naturally ends at0.175s. Maximum0.2s window unchanged; no audition/revalidation/timing gameplay proof. Native distances cm; no autoplay phase flags.'
(ev/'resolved-native-configuration.json').write_text(json.dumps(config,indent=2),encoding='utf-8')
d=yaml.safe_load((p/'map.yaml').read_text(encoding='utf-8'));ctrl=next(x for x in d['devices'] if x['id']=='controller');before=ctrl['settings']['learning_content'];ctrl['settings']['resolved_native_configuration']=config
for dev in d['devices']:
 if dev['id']=='hit_audio':
  dev['source']='Existing8 Audio Player actors repaired/saved to original project-owned imported Popcorn WAV; evidence/validation-audio-repair-native-resolved.json and saved-reference-audit.json';dev['settings']['asset']=asset+'; original0.175s source, unchanged guarded0.2s playback window'
for a in d['assumptions']:
 if a['id']=='a03_pop_audio':
  a['detail']='Existing8 players now reference original project-owned popcorn_hit_original SoundWave (native duration0.175s), synthesized from retained48kmonoPCM WAV with no sample/engine reuse. Same supported instigator/spatial/attenuation settings and0.175s guarded Stop+0.025s fade. Previous internal Fortnite wave was manually reported disallowed and is historical only. Native import/binding/save evidence supports corrective implementation; owner revalidation/mix remain unperformed.'
  a['evidence']='evidence/original-pop-audio-provenance-imported.json, validation-audio-repair-native-resolved.json, validation-audio-repair-saved-reference-audit.json and resolved-native-configuration.json. Asset loadability/type compatibility alone never establishes UEFN reference permission.'
assert ctrl['settings']['learning_content']==before
(p/'map.yaml').write_text(yaml.safe_dump(d,sort_keys=False,allow_unicode=True),encoding='utf-8')
plan=(p/'plan.md').read_text(encoding='utf-8');plan=plan.replace('Device_Call_End_Pop_01 (source0.392s)','the project-owned /fn_shoreline_island/Audio/popcorn_hit_original.popcorn_hit_original (original source0.175s)').replace('Audio0.2s window uses Stop plus short fade on a0.392s source','Audio0.2s maximum window uses unchanged Stop plus short fade on the original0.175s source')
plan+='''\n## Corrective project-owned audio pointer after owner validation failure\n\nOwner manual validation rejected all eight references to the prior internal Fortnite wave. Native loadability/type compatibility did not prove UEFN reference permission; that earlier configuration is archived under evidence/review-before-audio-permission-repair, and original approval history remains intact. Current operational map/settings use only /fn_shoreline_island/Audio/popcorn_hit_original.popcorn_hit_original.\n\nSupervisor imported Resources/Audio/popcorn_hit_original.wav into the project; the waveform is original synthesis by tools/create_popcorn_hit_audio.py from damped chirp/noise math, no engine or external sample. Retained WAV:48kHz mono16-bit PCM,8400 frames/0.175s; SHA2560ffa24c83dea5dd2011e1d3082cd31a187395221c786b16c1ef8afb7ba05841b. Native import metadata/duration and dependency list, all eight repaired audio pointers, unchanged settings and saves are captured in evidence/original-pop-audio-provenance-imported.json and validation-audio-repair*.json.\n\nThis is a nonmaterial corrective asset pointer under the actual approved short-pop scope, not a new lesson/layout/timing/reward design. Existing Stop0.175s/fade0.025s and maximum0.2s window are unchanged. No audition, tests, automatic Project Validate, cook or gameplay session was run for this repair; the owner must manually rerun validation and check sound mix/feedback. Saved native references do not constitute validation or gameplay acceptance. Current approval lineage records the same genuine user approval and this corrective revision without inventing a fresh human message.\n'''
(p/'plan.md').write_text(plan,encoding='utf-8')
report={'prior_review_digest':json.loads((ar/'review-manifest.json').read_text())['review_digest'],'old_restricted_asset':oldasset,'new_project_owned_asset':asset,'asset_pointer_only':True,'lessons_unchanged':True,'route_markers_unchanged':d['markers']==yaml.safe_load((ar/'map.yaml').read_text())['markers'],'timing_guard_unchanged':True,'new_human_approval_claimed':False,'project_validation_repeated':False,'native_evidence':['original-pop-audio-provenance-imported.json','validation-audio-repair-native-resolved.json','validation-audio-repair-saved-reference-audit.json']}
(ev/'audio-permission-correction-lineage.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print('Corrective audio pointer synchronized; prior review archived.')
