from pathlib import Path
import yaml,json,shutil,hashlib
p=Path('specs/041-popcorn-feedback-and-learning'); ev=p/'evidence'; original=ev/'approved-review-original';original.mkdir(exist_ok=True)
for name in ['preview.svg','preview.html','implementation.yaml','review-manifest.json']:
 shutil.copy2(p/'generated'/name,original/name)
shutil.copy2(p/'map.yaml',original/'map.yaml'); shutil.copy2(p/'approval.yaml',original/'approval.yaml')
old=json.loads((original/'review-manifest.json').read_text())['review_digest']
config={
 'halo':{'device_class':'/CRD_VFX_Creator/Assets/Device_VFX_Creator_V2.Device_VFX_Creator_V2_C','count':8,'sprite_table_row':'Shockwave','spriteShape':{'smallIcon':{'refPath':'/CRD_VFX_Creator/Assets/Icons_64/T_UI_IconLibrary_Shockwave01_64.T_UI_IconLibrary_Shockwave01_64'},'largeIcon':{'refPath':'/CRD_VFX_Creator/Assets/Icons_64/T_UI_IconLibrary_Shockwave01_64.T_UI_IconLibrary_Shockwave01_64'}},'resolved_texture':'/Game/Effects/Fort_Effects/Textures/Outlander/T_InTheZone_GroundRing_01.T_InTheZone_GroundRing_01','native_values':{'effectGenerationAmount':1,'spawnZoneShape':'Point','spriteRotationAlignment':'Planar','spriteSpeed':0,'effectGravity':0,'spriteDuration':0.5,'loop':'Never','loopDuration':0.5,'startEffectsWhenEnabled':False,'enabledDuringPhase':'Gameplay Only','spriteSize':0.65,'bKeepSize':False,'sizeOverTime':0.9,'useRandomColor':False,'mainColor':{'r':0.18,'g':0.9,'b':0.65,'a':1},'mainColorBrightness':2,'useSecondaryColor':True,'secondaryColor':{'r':0.18,'g':0.9,'b':0.65,'a':0},'secondaryColorBrightness':0.1},'lifecycle':'Controller independent Begin/End0.5s; no target-deactivate ownership; receiver ring orientation full native readback at binding; exact apparent diameter/fade manual calibration.'},
 'audio':{'device_class':'/CRD_AudioPlayer/Device_CRD_AudioPlayer.Device_CRD_AudioPlayer_C','catalogue':'/CRD_AudioPlayer/SetupAssets/PID_CP_Devices_CRD_AudioPlayer.PID_CP_Devices_CRD_AudioPlayer','count':8,'native_values':{'audio':{'refPath':'/Game/Sounds/Quests/SFX/Device/Device_Call_End_Pop_01.Device_Call_End_Pop_01'},'volume':0.35,'play On Hit':False,'can Be Heard By':'Instigator Only','play Location':'Device','loopAudio':False,'restart Audio When Activated':False,'enable Spatialization':True,'enable Volume Attenuation':True,'attenuation Function':'Linear','attenuation Min Distance':600,'attenuation Falloff Distance':1200,'fadeInDuration':0,'fadeOutDuration':0.025,'playDuringWaitingForPlayers':False,'playDuringGameCountdown':False,'playDuringGameplay':False,'playDuringRoundEnd':False,'playDuringGameEnd':False},'source_duration_seconds':0.3919999897480011,'playback_window_seconds':0.2,'stop_at_seconds':0.175,'lifecycle':'Explicit existing accept Play(agent), epoch-guarded Stop(agent) at0.175s plus0.025s fade; no audition, timing guarantee remains manual. Native distances cm. No autoplay phase flags.'},
 'hud':{'actor':'/fn_shoreline_island/fn_shoreline_island.fn_shoreline_island:PersistentLevel.Device_HUDMessage_V2_C_UAID_E89C2592D1B5160103_1360785784','native_values':{'placement':'Custom','screenAnchor':'Bottom Left','placementHorizontal':80,'placementVertical':-120,'layer':5,'message Priority':'Priority','allow Multiple in Queue':False,'queue Message for Join in Progress Players':False,'displayTimeOption':0,'override Default Text Style':True,'size':24,'messageCharLimit':500,'backgroundOpacity':80,'textColor':{'r':1,'g':1,'b':1,'a':1},'backgroundColor':{'r':0.015,'g':0.04,'b':0.08,'a':1}},'runtime':'Explicit Show(player,message,DisplayTime0), Hide(player) on journal/release. Lower-left intended composition via supported native offsets; fixed native widget wrap width/apparent safe margins checked manually, no invented width property. Preserve stage labels/action table.'},
 'journal':{'existing_source':'Content/fn_shoreline_island_academy_journal.verse panels[player]?canvas and show_panel/close_panel','integration':'Small is_panel_open(player)<transacts>:logic query of existing panels map; PopBridge presentation monitor watches changes and masks/resumes card. No progression/award authority changes.'}}
(ev/'resolved-native-configuration.json').write_text(json.dumps(config,indent=2),encoding='utf-8')
d=yaml.safe_load((p/'map.yaml').read_text());ctrl=next(x for x in d['devices'] if x['id']=='controller');ctrl['settings']['resolved_native_configuration']=config
for a in d['assumptions']:
 if a['id']=='a02_halo_asset':a.update(status='resolved',detail='Native Creator Shockwave ring sprite/table and one-shot Point/Planar/size/fade properties confirmed;8 independent controller refs remain approved implementation work, not placed/runtime evidence.',evidence='evidence/halo-vfx-native-schema.json, halo-sprite-candidates.json, halo-shockwave-texture-tags.json and resolved-native-configuration.json; duration/apparent size visibility are owner manual acceptance.')
 elif a['id']=='a03_pop_audio':a.update(status='resolved',detail='All8 hit_sound savedActor refs are null, so8 players need binding. Native Audio Player class and supported instigator/device-origin/spatial/attenuation/volume/no-loop settings confirmed; known Device_Call_End_Pop_01 wave metadata0.392s, faithful0.2s window via guarded Stop0.175s+0.025s fade.',evidence='evidence/target0..7-sound-native-ref.json, audio-native-schema.json, device-pop-wave-duration.json, resolved-native-configuration.json; no audition/cook/runtime mix proof claimed.')
 elif a['id']=='a04_hud_layout':a.update(status='resolved',detail='Existing feedback native actor Custom/BottomLeft offsets, layer5, Priority replacement, permanent displayTimeOption0, font/color/char limit are supported. Source journal panels map plus scoped query supports masking. Final wrapping/occlusion/readability are manual acceptance, not absent API blockers.',evidence='evidence/hud-saved-actor.json, hud-native-schema.json, hud-native-current-settings.json; existing journal source show_panel/close_panel/panels; resolved-native-configuration.json.')
for dev in d['devices']:
 if dev['id']=='hit_audio':dev['source']='All8 current target.hit_sound native wrappers unbound (savedActor=null); place/bind8 supported Audio Player devices using resolved_native_configuration';dev['settings']['asset']='Device_Call_End_Pop_01 native wave, guarded0.2s playback window';dev['settings']['attenuation_intent']='Native cm values600 minimum/1200 falloff; supported schema, manual mix calibration'
 if dev['id']=='hit_halos':dev['source']='Supported native Creator Shockwave sprite/table;8 separate refs to reconcile/place; not current native inventory';dev['settings']['asset']='Shockwave row in /CRD_VFX_Creator/Assets/DT_SpriteTable; GroundRing texture';dev['settings']['native_configuration']='controller.settings.resolved_native_configuration.halo'
 if dev['id']=='learning_hud':dev['settings']['placement_intent']='Supported Custom BottomLeft offsets80,-120; font24, white text, dark80% backdrop, layer5 Priority, permanent displayTimeOption0; native wrapping/manual readability pending'
(p/'map.yaml').write_text(yaml.safe_dump(d,sort_keys=False,allow_unicode=True),encoding='utf-8')
plan=(p/'plan.md').read_text()
plan+='''\n## Evidence-supported feasibility refinement after approval\n\nOwner approved original digest72c3683915afd8fbb567c216d611a1c27750330ca0fd90cd80ba7823170532eb and asked to build without testing. Original reviewed artifacts/approval/map are archived under evidence/approved-review-original. Native read-only evidence resolves asset/API support without changing lessons, geometry or intended behavior; see evidence/resolved-native-configuration.json for exact actor classes, property names/values and lifecycle. This refinement supersedes preceding statements that the native assets/HUD schema are unknown. Apparent size/fade, sound mix and HUD wrap/safe margins remain manual acceptance, not readiness blockers. No tests/QA/Project Validate/cook/PushChanges/StartGame authorized.\n\nEight target.hit_sound wrappers are actually unbound. Bind eight distinct Audio Players with Device_Call_End_Pop_01 (source0.392s); explicit accepted Play follows existing single accept call, guarded Stop at0.175s and native fadeOutDuration0.025 provides the approved0.2s window. To enforce existing proposed global0.15s cosmetic sound gap while retaining all accepted signals, allow a backward-compatible optional play_audio argument on data_target.accept, default true for every existing caller. Only PopBridge passes its cosmetic eligibility; no other mission/default changes. This is a routine internal adapter refinement within preserved shared behavior, replacing the earlier absolute untouched-class preference where necessary. Do not call accept twice or affect fixture/progress eligibility.\n\nCreator Shockwave row selects a known GroundRing texture with Point spawn, one sprite, Planar facing, Never loop,0.5s lifetime, soft mint glow and secondary alpha fade. Standalone controller refs exclude target activate/deactivate; native calibration values are declared in the configuration file. Do not guess a distinct128px icon path: the small64px table icon is also supplied as the largeIcon texture ref, a valid Texture2D native type.\n\nHUD permanent option uses native displayTimeOption0 (the ordinary displayTime property has minimum1 and must not be set0). Native Custom/BottomLeft+80,-120 offsets/font24/white-dark backdrop/char limit500 replace schematic percentage placement; native widget wraps without a fabricated width field. Priority replaces, no multiple/JIP queue, layer5 already dedicated feedback. Same exact three-line copy; journal source panels map supports a narrow visibility-query helper and PopBridge monitors visibility changes to hide/resume latest card. Native context uses no new UI or reward flow.\n'''
(p/'plan.md').write_text(plan,encoding='utf-8')
review=(p/'review.md').read_text();review+='''\n## Live read-only feasibility resolution after owner approval\n\nOfficial MCP restored by Supervisor, exclusive read-only ownership transferred to Planner. Serialized tool schemas and exact native reads are in evidence/*.json. GetGameState returned Unconnected. All8 hit_sound wrappers have savedActor=null; the absence of configured sounds is measured. Supported native Creator Shockwave row/table/texture, Audio Player class/settings and Device_Call_End_Pop_01 metadata, and current HUD/native permanent option plus source journal query remove A02–A04 support blockers. Exact resolved setup is evidence/resolved-native-configuration.json. No source/native mutations, tests, auditions, sessions or compile performed by Planner.\n\nThis is a nonmaterial asset/API refinement of approved feedback, retaining every approved lesson verbatim and all041 requirements/040 geometry. Existing native schema constraints replace guessed screen percentages and unknown assets. Audio0.2s window uses Stop plus short fade on a0.392s source; apparent pulse size/fade, effective onset/audio mix/readability/cook suitability remain owner manual acceptance. Original reviewed bundle and approval remain archived. Current approval digest follows this faithful refinement with explicit lineage to the actual user instruction; no new human approval is fabricated.\n''';(p/'review.md').write_text(review,encoding='utf-8')
print('native refinement drafted; original digest',old)
