from pathlib import Path
import yaml,json,math
p=Path('specs/042-popcorn-finish-hub-portal');d=yaml.safe_load(Path('specs/041-popcorn-feedback-and-learning/map.yaml').read_text(encoding='utf-8'));d['map'].update(id='popcorn_finish_hub_portal',title='Popcorn finish: walk into the Hub portal',source_feature='specs/042-popcorn-finish-hub-portal/spec.md',size=[50,210,8],min_path_width=1.2,learning_objective='Complete PopBridge reuse, then choose the visible Hub exit while retaining earned progress. No extra learning action or quiz.')
d['player_flow']=['course','finish_portal','hub'];z=d['zones'][0];z['overlap_with']=['finish_portal'];z['purpose']='Existing mirrored Popcorn course preserved; finish portal appears/enables only after target7 successful completion and existing reward call.'
ctrl=next(v for v in d['devices'] if v['id']=='controller');contract=ctrl['settings']['course_contract'];ctrl['settings']={'reuse_existing':True,'course_contract':contract,'preserve041':'All accepted hit/learning/cancellation/audio settings and existing completion popup, journal/rewards unchanged except final action guidance','portal_contract':{'label':'pop042_finish_hub_portal','new_editable':'finish_hub_portal:teleporter_device','world_transform':{'location':{'x':-4900,'y':-17320,'z':2600},'rotation':{'pitch':0,'yaw':0,'roll':0},'scale':{'x':1,'y':1,'z':1}},'native_class':'/CreativeCoreDevices/Device_Teleporter_V2.Device_Teleporter_V2_C','catalogue':'/CreativeCoreDevices/SetupAssets/PID_Device_Teleporter.PID_Device_Teleporter','native_settings':{'enabledDuringPhase':'None','knob_TeleporterGroup':'Group_None','knob_TargetTeleporterGroup':'Group_None','teleporter Rift Visible':True,'play Visual Effects':True,'play Sound Effects':True,'can Teleport Physics Props':False,'skydive After Teleport':False},'gate':'Same owner/attempt generation/round, actual finished state, after synchronous existing progress.complete_challenge(player,2) returns; no raw-hit unlock','entry':'EnterEvent -> guard owned finished ready token/round/bay -> close gate/disable -> existing return_to_hub(agent), which release-cleans then hub_destination.Teleport(agent)','fresh_entry':'After rewardReady, keep Disabled until current owner horizontal distance from portal centre is >1.0m. Existing sync_card monitor (0.1s) rechecks owner/token/round/finished before arming; this prevents Enable while owner overlaps. Then fresh EnterEvent only.', 'closed':'Startup/release/Replay/Return/round/departure/removal disable; finished visibility/state cannot leak to next attempt','approach':'Walk2.4m from finish centre to portal; native capsule reference effective XY radius0.44m,halfheight0.616m,portal centre0.8m above deckfeet','copy':'Walk into the glowing HUB portal, or use Return.', 'completion_card':'Mission complete! You saved three steps and reused them.\nPopBridge = LOAD > HEAT > POP.\nWalk into the glowing HUB portal, or use Return.', 'completion_card_characters':136},'hub_destination_ref':'/fn_shoreline_island/fn_shoreline_island.fn_shoreline_island:PersistentLevel.Device_Teleporter_V2_C_UAID_E89C2592D1B5C80003_1842943040','hub_destination_world_transform':'Measured(-700,1500,2500)cm,yaw90,scale1; reuse unchanged','adapter_choice':'Small PopBridge optional completion_ready hook after existing reward plus production portal handler/gate; existing shared return path retained. SDK supports API; implementation pending actual approval.'}
# Inventory existing course supports succinctly; do not replay prior presentation/asset changes.
for v in d['devices']:
 if v['id']!='controller':v['settings']={'reuse_existing':True,'preserve':'Existing041 saved settings/bindings; no042 change to this group'}
d['devices'].append({'id':'finish_hub_portal','class':'teleporter_device','count':1,'source':'Proposed one new native V2 Teleporter; current catalog/schema/capsule readback under042 evidence; existing hub_destination reused','settings':ctrl['settings']['portal_contract']})
d['zones'] += [{'id':'finish_portal','label':'Finish Hub portal (completion-gated)','pattern':'portal','position':[1.4,15.4,1.2],'size':[3.2,2.8,2.8],'purpose':'Small informational interaction envelope on existing finish deck, not a new room/floor; deliberate spare-space walk-in exit after mission completion.','parameters':{'destination':'hub','bidirectional':False},'devices':['finish_hub_portal','controller'],'overlap_with':['course'],'completion':'Owned finished player enters, cleanup-first same Hub destination; no new reward','reset':'Disable and invalidate gate before attempt reset/round/Return; preserve badge'}, {'id':'hub','label':'Existing Hub destination annotation','pattern':'corridor','position':[43.5,203.5,0],'size':[3,3,3],'purpose':'Estimated annotation envelope around measured existing Hub teleporter; no new corridor/floor/actor or Hub layout edit. Same arrival used by existing Returns.','parameters':{'width_m':3,'access':'Existing Hub arrival, no geometry mutation'},'devices':[],'overlap_with':[],'completion':'Player has returned to existing Hub destination','reset':'No change to Hub settings'}]
d['connections']=[{'from':'course','to':'finish_portal','mode':'walk','width':1.2,'points':[[3,19.2,1.2],[3,16.8,1.2]],'gate':'finale'},{'from':'finish_portal','to':'hub','mode':'portal','width':1.2,'points':[[3,16.8,1.2],[45,205,1]],'gate':'finale'}]
d['markers'] += [{'id':'finish_portal_entry','kind':'exit','zone':'finish_portal','label':'Glowing HUB portal; walk in after completion','position':[3,16.8,1.2],'source':'Proposed feet approach position; actor centre(-4900,-17320,2600)cm/scale1 uses measured native overlap dimensions. Existing deck measuredtop2520; no deck mutation.'},{'id':'hub_arrival','kind':'exit','zone':'hub','label':'Existing Hub destination; unchanged','position':[45,205,1],'source':'Measured current hub_destination native actor pivot(-700,1500,2500)cm,yaw90,scale1. Envelope is annotation, not a floor claim.'}]
d['stages'] += [{'id':'walk_in_return','zone':'finish_portal','purpose':'Choose visible Hub return after completing the saved skill course','requires':['finale'],'active_targets':[],'completion':'Owned finished player enters unlocked portal; controller closes gate/releases then calls existing Hub Teleport'},{'id':'hub_arrival','zone':'hub','purpose':'Retain earned Skills progress while continuing Academy from Hub','requires':['walk_in_return'],'active_targets':[],'completion':'Existing Hub arrival, no additional lesson/reward authority'}]
d['assumptions']=[{'id':'a01_supported_api','status':'resolved','detail':'Local Fortnite SDK exposes teleporter EnterEvent,Enable,Disable,Teleport; native V2 catalogue/groupNone/startNone/visible-effect options measured. EnterEvent with GroupNone is SDK-supported input intent, runtime overlap remains manual acceptance. No new transport engine.','evidence':'042 evidence/teleporter-native-schema.json,teleporter-catalogue.json,teleporter-native-supported-settings.json; localFortnite.digest.verse5755..5791'}, {'id':'a02_finish_clearance','status':'resolved','detail':'Finish deck bounds measured X[-5100,-4700],Y[-17480,-16680],top2520. Proposed centre(-4900,-17320,2600),scale1,yaw0,default capsule effective44cmXYradius/61.6cmhalfheight, leaves156cmX and116cmnearestYedge clearance. Standing capsule can overlap at deckfeet; no jump/step/deck change. Physical body clearance/effect readability verified manually later.','evidence':'042 evidence/finish-deck-native-bounds.json,teleporter-overlap-capsule-values.json; currentstanding feet offset77.15cm in controller'}, {'id':'a03_cleanup_destination','status':'resolved','detail':'Reuse same hub_destination actor/currenttransform and existing release->Teleport return path. Completion hook opens gate after successful final commit/reward call; callbacks recheck owner/generation/round/finished and synchronous close prevents duplicate/stale entry. Narrow planned adapter uses existing APIs/state, no extra authority.','evidence':'Current PopBridge controller execute,release,return_to_hub; production release_owner;042 known-native-refs andhub_destination-native-transform.json'}, {'id':'a04_manual_verification','status':'resolved','detail':'Existing owner no-testing instruction continues: no tests/QA/ProjectValidate/cook/push/session. Compile/readback/save remain implementation hygiene; owner manually verifies overlap/arrival/gating and preserved course. This is an explicit delivery constraint, not a claim of gameplay pass.','evidence':'041 evidence/human-approval-and-manual-testing.md; currentSupervisor instructions'}]
class NoAliasDumper(yaml.SafeDumper):
 def ignore_aliases(self,data):return True
(p/'map.yaml').write_text(yaml.dump(d,Dumper=NoAliasDumper,sort_keys=False,allow_unicode=True),encoding='utf-8')

# Current repair adapter is maintained in map.yaml; archive is historical, not a regeneration source.
