import importlib,json,pathlib
m=importlib.import_module('implementation-client');P=m.P
portal=json.loads(pathlib.Path('specs/042-popcorn-finish-hub-portal/evidence/portal-resolved.json').read_text())
popup=json.loads((P/'popup-resolved.json').read_text())
binding=json.loads((P/'binding-resolved.json').read_text())
prims=m.unpack(json.loads((P/'popup-primitives.json').read_text()))
script='import json\n\ndef values(ref,keys):\n    return json.loads(execute_tool("editor_toolset.toolsets.object.ObjectTools.get_properties",json.dumps({"instance":ref,"properties":keys}))["returnValue"])\n\ndef transform(ref):\n    return execute_tool("editor_toolset.toolsets.actor.ActorTools.get_actor_transform",json.dumps({"actor":ref}))["returnValue"]\n\ndef package(ref):\n    return execute_tool("editor_toolset.toolsets.scene.SceneTools.get_actor_asset_path",json.dumps({"actor":ref}))["returnValue"]\n\ndef dirty(path):\n    return execute_tool("editor_toolset.toolsets.asset.AssetTools.is_dirty",json.dumps({"asset_path":path}))["returnValue"]\n\ndef run():\n    portal=PORTAL\n    popup=POPUP\n    binding=BINDING\n    result={"portal_transform":transform(portal["actor"]),"portal_settings":values(portal["actor"],list(portal["settings"])),"popup_transform":transform(popup["actor"]),"popup_settings":values(popup["actor"],list(popup["settings"])),"binding":values(binding["wrapper"],["savedActor"]),"primitives":[{"ref":p,"values":values(p,["bHiddenInGame","bIsEditorOnly","bRenderInMainPass","bodyInstance"])} for p in PRIMS]}\n    if result["portal_transform"]!=portal["transform"] or result["portal_settings"]!=portal["settings"]:raise RuntimeError("Portal modified")\n    if result["popup_transform"]!=popup["transform"] or result["popup_settings"]!=popup["settings"]:raise RuntimeError("Popup settings did not persist")\n    if result["binding"]["savedActor"]!=popup["actor"]:raise RuntimeError("Popup binding missing")\n    for c in result["primitives"]:\n        v=c["values"]\n        if not v["bIsEditorOnly"]:\n            if v["bodyInstance"]["collisionEnabled"]!="NoCollision" or not v["bHiddenInGame"] or v["bRenderInMainPass"]:raise RuntimeError("Runtime primitive not inert")\n    paths={"popup":package(popup["actor"]),"controller":package(binding["controller"]),"map":"/fn_shoreline_island/fn_shoreline_island"}\n    result["packages"]=paths\n    result["dirty"]={k:dirty(v) for k,v in paths.items()}\n    if any(result["dirty"].values()):raise RuntimeError("Dirty packages")\n    return result\n'.replace('PORTAL',repr(portal)).replace('POPUP',repr(popup)).replace('BINDING',repr(binding)).replace('PRIMS',repr(prims))
r=m.call('final-native-audit','editor_toolset.toolsets.programmatic.ProgrammaticToolset','execute_tool_script',{'script':script});(P/'final-native-audit-resolved.json').write_text(json.dumps(r,indent=2))
m.call('final-game','ValkyrieToolset.SessionToolset','GetGameState',{})
m.call('final-session','ValkyrieToolset.SessionToolset','GetSessionStatus',{})
