from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
p=Path('specs/043-popcorn-hub-return-confirmation');g=p/'generated';im=Image.new('RGB',(1100,760),'#0d1728');d=ImageDraw.Draw(im)
def F(n,b=False):return ImageFont.truetype('C:/Windows/Fonts/segoeuib.ttf' if b else 'C:/Windows/Fonts/segoeui.ttf',n)
d.text((45,30),'Choose before returning',font=F(35,True),fill='white');d.text((45,86),'Finish the mission → enter the existing glowing portal → see this dialog',font=F(22),fill='#c9d8ec')
d.rounded_rectangle((170,170,930,490),radius=20,fill='#213753',outline='#78dff2',width=2)
d.text((220,207),'Return to Hub?',font=F(32,True),fill='white');d.text((220,275),'Mission complete!',font=F(22),fill='#edf5ff');d.text((220,310),'Return to the hub now?',font=F(22),fill='#edf5ff')
d.rounded_rectangle((220,390,550,450),radius=9,fill='#51e2ef');d.text((280,403),'Return to Hub',font=F(24,True),fill='#102237');d.rounded_rectangle((580,390,880,450),radius=9,fill='#384f70');d.text((687,403),'Cancel',font=F(24,True),fill='white')
d.text((65,545),'Return to Hub',font=F(23,True),fill='#51e2ef');d.text((65,585),'Go to the same Hub arrival.',font=F(20),fill='white');d.text((65,620),'Keep earned progress.',font=F(20),fill='white')
d.text((610,545),'Cancel or Back',font=F(23,True),fill='#b8baff');d.text((610,585),'Stay on the finish deck.',font=F(20),fill='white');d.text((610,620),'Step clear, then re-enter to ask again.',font=F(20),fill='white')
d.text((45,704),'Proposal • native dialog styling may differ • no countdown or automatic return',font=F(19),fill='#c9d8ec');im.save(g/'confirmation-review.png')
(g/'confirmation-review.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><title>Confirm Hub return</title><style>body{background:#0d1728;color:#edf5ff;font:18px/1.6 system-ui;max-width:1100px;margin:24px auto}img{width:100%}section{background:#213753;padding:22px;border-radius:14px}a{color:#51e2ef}</style></head><body><img src="confirmation-review.png" alt="Confirmation dialog: Return to Hub or Cancel"><section><p>The existing portal stays in place. After completing the mission, entering it opens this dialog. Only choosing <strong>Return to Hub</strong> teleports you; <strong>Cancel</strong> or Back keeps you at the finish.</p><p>The dialog won't repeat while you stand inside. Step clear and re-enter to ask again. Existing Return buttons and Replay remain available. Earned progress is kept.</p><p>One supporting native dialog device; no layout or portal changes. Implementation awaits explicit approval. Behavior will be checked manually by the owner.</p><a href="../plan.md">Concrete plan</a> · <a href="../review.md">Review findings</a> · <a href="preview.html">Unchanged course and portal overview</a></section></body></html>''',encoding='utf-8')
